version: '3.8'

services:
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"

  mercure-sse:
    container_name: mercure-sse
    image: dunglas/mercure
    restart: always
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':1405'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:4200 https://epitalk.api.dibodev.fr https://epitalk.dibodev.fr
        anonymous
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "1405:1405"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  db_data:
