version: '3.8'

services:
  adonis_backend:
    image: node:lts
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c "npm install && node ace serve --watch"
    ports:
      - "3333:3333"
    networks:
      - app-network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: irc
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - app-network

  mercure-sse:
    image: dunglas/mercure
    restart: always
    environment:
      # Uncomment the following line to disable HTTPS
      SERVER_NAME: ':1405'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins "http://localhost:5173"
        anonymous
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
    ports:
      - "1405:1405"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  app-network:
